2023-07-22 00:05:47,537 - [error_logger] - [window.addEventListerner('message')] - HTTPConnectionPool(host='localhost', port=55521): Max retries exceeded with url: /session/117f40aa836af6ebcdccb8d86f088153/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection obje
2023-07-22 00:05:47,596 - [error_logger] - [window.addEventListerner('message')] - HTTPConnectionPool(host='localhost', port=52655): Max retries exceeded with url: /session/71534e5b22cb932461c74fd21e546ccb/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection obje
2023-07-22 00:05:47,630 - [error_logger] - [window.addEventListerner('message')] - HTTPConnectionPool(host='localhost', port=36495): Max retries exceeded with url: /session/dd9aa052459f574200eba71238083294/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection obje
2023-07-22 00:05:47,682 - [error_logger] - [window.addEventListerner('message')] - HTTPConnectionPool(host='localhost', port=60903): Max retries exceeded with url: /session/1487c286512eca6d93b20ada6ebb586e/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection obje
2023-07-22 00:20:58,436 - [error_logger] - [window.addEventListerner('message')] - HTTPConnectionPool(host='localhost', port=55337): Max retries exceeded with url: /session/4466c9ef79a72279eb715c8b7bdf9567/alert/text (Caused by NewConnectionError('<urllib3.connection.HTTPConnection 
2023-07-22 00:20:58,569 - [error_logger] - [window.addEventListerner('message')] - HTTPConnectionPool(host='localhost', port=53761): Max retries exceeded with url: /session/6a3b38443f1f56082cc56d7f44b19195/alert/text (Caused by NewConnectionError('<urllib3.connection.HTTPConnection 
2023-07-22 00:20:58,650 - [error_logger] - [window.addEventListerner('message')] - HTTPConnectionPool(host='localhost', port=42719): Max retries exceeded with url: /session/f9a91654d94ef554c4a6885e3991fd5e/alert/text (Caused by NewConnectionError('<urllib3.connection.HTTPConnection 
2023-07-22 00:20:58,813 - [error_logger] - [window.addEventListerner('message')] - HTTPConnectionPool(host='localhost', port=45221): Max retries exceeded with url: /session/6e1d5c4d5bfb7fdccbacb3219f0d2b08/alert/text (Caused by NewConnectionError('<urllib3.connection.HTTPConnection 
